### PR TITLE
Expose blacklist and whitelist values on description

### LINKED ISSUE #883: scheme.describe omits whitelist and blacklist
**Describe the bug**
[schema.describe](https://github.com/jquense/yup/blob/master/src/mixed.js#L532-L542) does not expose the whitelist or blacklists maintained by [oneOf](https://github.com/jquense/yup/blob/master/src/mixed.js#L470-L471)

**To Reproduce**
https://codesandbox.io/s/nice-wilson-egh66?file=/src/index.test.js
```js
const yup = require("yup");
const assert = require("assert");

it("should pass", async () => {
  const schema = yup.object({
    name: yup.string().oneOf(["a", "b", "c"])
  });

  const description = schema.describe();
  assert.deepEqual(description.whitelist, ["a", "b", "c"]);
});
```

**Expected behavior**
The whitelist and blacklists to be accessible (as either sets or arrays) through schema.describe();

**Additional context**
I would like to use this to generate test data for [yup-by-example](https://github.com/cressie176/yup-by-example). I would be happy to submit a PR.

### PR DESCRIPTION
**Pull request by dreamsinspace**
Closes #883

### CODE REVIEW

File: src/mixed.js [hunk 1]
```diff
@@ -538,7 +548,12 @@ const proto = (SchemaType.prototype = {
         .filter(
           (n, idx, list) => list.findIndex(c => c.name === n.name) === idx,
         ),
-    };
+    }
+
+    if (next._whitelist.size) description.whitelist = next._whitelist.describe();
```
Comment (jquense) [inline src/mixed.js:553]: lets call these `oneOf` and `notOneOf` to match the method name, it'll involve a little less mental overhead mapping schema to descriptions etc

Comment (dreamsinspace) [reply src/mixed.js:553]: Sure thing @jquense

**Comment by dreamsinspace** [comment]
Np, glad it gets merged.
