### PR TITLE
Handle sparse array positions as undefined V2

### LINKED ISSUE #676: TypeError: Cannot read property 'fulfilled' of undefined
**Describe the bug**
I have a Codesandbox running a library called React Hook Form. If you add two friends in the code pen and then remove the first friend and then submit the form you see the error. The stack trace shows the error at a line in react-hook-form.js. BUT if you dig deeper the error is actually coming from line 84 of runValidations.js where the check for !r.fulfilled throws an error saying:

`"TypeError: Cannot read property 'fulfilled' of undefined
    at eval (eval at <anonymous> (https://yycrz.csb.app/node_modules/yup/lib/util/runValidations.js), <anonymous>:1:3)
    at eval (https://yycrz.csb.app/node_modules/yup/lib/util/runValidations.js:84:17)
    at Array.filter (<anonymous>)
    at eval (https://yycrz.csb.app/node_modules/yup/lib/util/runValidations.js:83:32)
    at async Promise.all (index 0)
    at async validateWithSchema (https://yycrz.csb.app/node_modules/react-hook-form/dist/react-hook-form.js:383:21)
    at async eval (https://yycrz.csb.app/node_modules/react-hook-form/dist/react-hook-form.js:886:28)"`

**To Reproduce**
https://codesandbox.io/s/react-hook-form-array-fields-validation-using-refs-yycrz?from-embed

Add two friends and then delete one friend. When you submit the form, you can see the error Chrome dev tools.

> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

**Expected behavior**
Handle the scenario where r is undefined to fail gracefully so it does not break the running script.

**Platform (please complete the following information):**

**Additional context**
Also, one of the folks at React Hook Form asked me to share this screenshot:
1b0f20e8-8e5b-4b01-ac56-5ab844645213-Screen%20Shot%202019-10-26%20at%208 52 04%20am (1)

### PR DESCRIPTION
**Pull request by VanTanev**
Superseeds #949; Fixes #676

Yup validation no longer throws on sparse arrays:
```javascript
let schema = y.array(number())
let arr = []
arr[1] = 1
arr
// => [empty, 1]

// fixes TypeError: Cannot read property 'fulfilled' of undefined
schema.validate(arr, {
  abortEarly: false,
  context: {},
})
```
---

Yup required validation now treats empty slots in sparse arrays as missing:
```javascript
let schema = y.array(y.number().required())
let arr = []
arr[1] = 1
arr
// => [empty, 1]

await schema.isValid(arr) // false
await schema.compact().isValid(arr) // true
```

---

Yup preserves empty slots in sparse arrays when valid:
```javascript
let schema = y.array(y.number())
let arr = []
arr[1] = 1
arr
// => [empty, 1]

let value = await schema.validate(arr)

0 in value 
// => false
```

### CODE REVIEW

**Comment by jquense** [comment]
https://github.com/jquense/yup/pull/949#discussion_r445026738

File: src/array.js [hunk 1]
```diff
@@ -84,8 +84,12 @@ inherits(ArraySchema, MixedSchema, {
 
         originalValue = originalValue || value;
 
-        let validations = value.map((item, idx) => {
-          var path = makePath`${options.path}[${idx}]`;
+        let len = value.length;
+        let idx = -1;
+        let validations = new Array(len);
+        while (++idx < len) {
```
Comment (jquense) [inline src/array.js:90]: i'd write this as a normal `for` loop it's also fine to not cache the length value as a separate variable

File: test/array.js [hunk 2]
```diff
@@ -202,4 +202,19 @@ describe('Array types', () => {
...
       .validate(value);
   });
+
+  it('should treat sparse arrays empty slots as undefined for the purpose of validation', async () => {
+    let sparseArray = new Array(2);
+    sparseArray[1] = 1;
+    let value = await array().of(number()).validate(sparseArray);
+    expect(0 in sparseArray).to.be.false()
+    expect(0 in value).to.be.false()
+    value.should.eql([undefined, 1]);
```
Comment (jquense) [inline test/array.js:212]:
```suggestion
    value.should.eql([, 1]);
```

more clearly signals that this should be sparse

File: test/array.js [hunk 3]
```diff
@@ -202,4 +202,19 @@ describe('Array types', () => {
       .of(itemSchema)
       .validate(value);
   });
+
+  it('should treat sparse arrays empty slots as undefined for the purpose of validation', async () => {
```
Comment (jquense) [inline test/array.js:206]: should 
```suggestion
  it('should maintain array sparseness through validation', async () => {
```

File: test/array.js [hunk 4]
```diff
@@ -202,4 +202,19 @@ describe('Array types', () => {
...
+    let sparseArray = new Array(2);
+    sparseArray[1] = 1;
+    let value = await array().of(number()).validate(sparseArray);
+    expect(0 in sparseArray).to.be.false()
+    expect(0 in value).to.be.false()
+    value.should.eql([undefined, 1]);
+  });
+
+  it('should treat required sparse arrays empty slots as invalid', async () => {
```
Comment (jquense) [inline test/array.js:215]:
```suggestion
  it('should empty slots in sparse arrays', async () => {
```

File: src/array.js (hunk 1 above)
Comment (VanTanev) [reply src/array.js:90]: Roger, will do!

I picked up this style from lodash's source code, but it's probably better to use the more readable `for` here.

File: src/array.js [hunk 5]
```diff
@@ -84,8 +84,10 @@ inherits(ArraySchema, MixedSchema, {
 
         originalValue = originalValue || value;
 
-        let validations = value.map((item, idx) => {
-          var path = makePath`${options.path}[${idx}]`;
+        let validations = new Array(value.length);
```
Comment (jquense) [inline src/array.js:87]:
```suggestion
        // #950 Ensure that sparse array empty slots are validated
        let validations = new Array(value.length);
```

**Comment by jquense** [comment]
thanks!
