### PR TITLE
Do not initialize spec values with undefined

### LINKED ISSUE #1160: baseSchema.concat(otherSchema) overwrites baseSchema properties when otherSchema properties are undefined
**Describe the bug**
Last_Edit: It is because of this code https://github.com/jquense/yup/blob/master/src/schema.ts#L231-L233 , `combined.spec` has every property `undefined`, it would work if `combined.spec` properties were non-existent instead of `undefined`:

`const mergedSpec = { ...base.spec, ...combined.spec };`

First_Edit: Looking a bit deeper, i am now not sure if it is caused by mixed.label(), but since the only thing we change is the yup version and this unexpected behavior occurs, i will keep this issue as is, hopefully someone experienced in yup can investigate or realize the reason why this happens.

Calling mixed.label("Custom label") does work on version 0.31.0 but not on 0.32.5+.
Example screenshots from v.0.31.0 and v.0.32.5+
v.0.31.0:

before_update

v.0.32.5+:

after_update

**To Reproduce**
Quite complex form logic react and formik, will try to extract the logic and edit here.

**Expected behavior**
I would expect the previous behavior of setting a label to work on error messages.

**Platform (please complete the following information):**
 - Browser [chrome]
 - Version [86]

**Additional context**
Using with react + formik

### PR DESCRIPTION
**Pull request by cemalettin-simsoft**
Otherwise spreading spec values like previously would overwrite the base schema spec values with undefined.
Closes #1160.

### CODE REVIEW

**Comment by jquense** [comment]
thanks for the PR, i'd need some context for why this behavior should be changed and tests as well

**Comment by jquense** [comment]
oops sorry i didn't see the linked issue 👍

File: src/schema.ts [hunk 1]
```diff
@@ -229,7 +229,14 @@ export default abstract class BaseSchema<
     let base = this;
     let combined = schema.clone();
 
-    const mergedSpec = { ...base.spec, ...combined.spec };
+    const baseSpec = { ...base.spec };
+    // only overwrite with spec values which are not undefined
+    const mergedSpec = Object.keys(combined.spec).reduce((accum, key) => {
```
Comment (jquense) [inline src/schema.ts:234]: i think it probably simpler to not define undefined properties in the spec instead and keep the object spread

Comment (cemalettin-simsoft) [reply src/schema.ts:234]: Yes, that was the other option, i wasn't really sure about editing that part, it may depend on other stuff as well, not too familiar with yup.

**Review by jquense — APPROVED** [review]

**Comment by jquense** [comment]
thanks!
